// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/pathcraft/v1/pathcraft.proto

package pathcraftv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TravelMode int32

const (
	TravelMode_TRAVEL_MODE_UNSPECIFIED TravelMode = 0
	TravelMode_TRAVEL_MODE_WALK        TravelMode = 1
	TravelMode_TRAVEL_MODE_BIKE        TravelMode = 2
	TravelMode_TRAVEL_MODE_CAR         TravelMode = 3
)

// Enum value maps for TravelMode.
var (
	TravelMode_name = map[int32]string{
		0: "TRAVEL_MODE_UNSPECIFIED",
		1: "TRAVEL_MODE_WALK",
		2: "TRAVEL_MODE_BIKE",
		3: "TRAVEL_MODE_CAR",
	}
	TravelMode_value = map[string]int32{
		"TRAVEL_MODE_UNSPECIFIED": 0,
		"TRAVEL_MODE_WALK":        1,
		"TRAVEL_MODE_BIKE":        2,
		"TRAVEL_MODE_CAR":         3,
	}
)

func (x TravelMode) Enum() *TravelMode {
	p := new(TravelMode)
	*p = x
	return p
}

func (x TravelMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TravelMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pathcraft_v1_pathcraft_proto_enumTypes[0].Descriptor()
}

func (TravelMode) Type() protoreflect.EnumType {
	return &file_api_pathcraft_v1_pathcraft_proto_enumTypes[0]
}

func (x TravelMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TravelMode.Descriptor instead.
func (TravelMode) EnumDescriptor() ([]byte, []int) {
	return file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP(), []int{0}
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RouteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Origin             *Coordinate            `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination        *Coordinate            `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Mode               TravelMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=pathcraft.v1.TravelMode" json:"mode,omitempty"`
	IncludeCoordinates bool                   `protobuf:"varint,4,opt,name=include_coordinates,json=includeCoordinates,proto3" json:"include_coordinates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP(), []int{1}
}

func (x *RouteRequest) GetOrigin() *Coordinate {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *RouteRequest) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *RouteRequest) GetMode() TravelMode {
	if x != nil {
		return x.Mode
	}
	return TravelMode_TRAVEL_MODE_UNSPECIFIED
}

func (x *RouteRequest) GetIncludeCoordinates() bool {
	if x != nil {
		return x.IncludeCoordinates
	}
	return false
}

type RouteResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds                       []int64                `protobuf:"varint,1,rep,packed,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	Coordinates                   []*Coordinate          `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	DistanceMeters                float64                `protobuf:"fixed64,3,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationSeconds               int64                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	OriginNodeId                  int64                  `protobuf:"varint,5,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	DestinationNodeId             int64                  `protobuf:"varint,6,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	OriginSnapDistanceMeters      float64                `protobuf:"fixed64,7,opt,name=origin_snap_distance_meters,json=originSnapDistanceMeters,proto3" json:"origin_snap_distance_meters,omitempty"`
	DestinationSnapDistanceMeters float64                `protobuf:"fixed64,8,opt,name=destination_snap_distance_meters,json=destinationSnapDistanceMeters,proto3" json:"destination_snap_distance_meters,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP(), []int{2}
}

func (x *RouteResponse) GetNodeIds() []int64 {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *RouteResponse) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *RouteResponse) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *RouteResponse) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *RouteResponse) GetOriginNodeId() int64 {
	if x != nil {
		return x.OriginNodeId
	}
	return 0
}

func (x *RouteResponse) GetDestinationNodeId() int64 {
	if x != nil {
		return x.DestinationNodeId
	}
	return 0
}

func (x *RouteResponse) GetOriginSnapDistanceMeters() float64 {
	if x != nil {
		return x.OriginSnapDistanceMeters
	}
	return 0
}

func (x *RouteResponse) GetDestinationSnapDistanceMeters() float64 {
	if x != nil {
		return x.DestinationSnapDistanceMeters
	}
	return 0
}

type JourneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        *Coordinate            `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *Coordinate            `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartureTime string                 `protobuf:"bytes,3,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	MaxStopCount  int32                  `protobuf:"varint,4,opt,name=max_stop_count,json=maxStopCount,proto3" json:"max_stop_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JourneyRequest) Reset() {
	*x = JourneyRequest{}
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyRequest) ProtoMessage() {}

func (x *JourneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyRequest.ProtoReflect.Descriptor instead.
func (*JourneyRequest) Descriptor() ([]byte, []int) {
	return file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP(), []int{3}
}

func (x *JourneyRequest) GetOrigin() *Coordinate {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *JourneyRequest) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *JourneyRequest) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *JourneyRequest) GetMaxStopCount() int32 {
	if x != nil {
		return x.MaxStopCount
	}
	return 0
}

type JourneyResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Mode                   string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	DepartureTime          string                 `protobuf:"bytes,2,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime            string                 `protobuf:"bytes,3,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	TotalDurationSeconds   int64                  `protobuf:"varint,4,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	TransitDurationSeconds int64                  `protobuf:"varint,5,opt,name=transit_duration_seconds,json=transitDurationSeconds,proto3" json:"transit_duration_seconds,omitempty"`
	WalkingDistanceMeters  float64                `protobuf:"fixed64,6,opt,name=walking_distance_meters,json=walkingDistanceMeters,proto3" json:"walking_distance_meters,omitempty"`
	Legs                   []*JourneyLeg          `protobuf:"bytes,7,rep,name=legs,proto3" json:"legs,omitempty"`
	OriginStopId           string                 `protobuf:"bytes,8,opt,name=origin_stop_id,json=originStopId,proto3" json:"origin_stop_id,omitempty"`
	DestinationStopId      string                 `protobuf:"bytes,9,opt,name=destination_stop_id,json=destinationStopId,proto3" json:"destination_stop_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JourneyResponse) Reset() {
	*x = JourneyResponse{}
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyResponse) ProtoMessage() {}

func (x *JourneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyResponse.ProtoReflect.Descriptor instead.
func (*JourneyResponse) Descriptor() ([]byte, []int) {
	return file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP(), []int{4}
}

func (x *JourneyResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *JourneyResponse) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *JourneyResponse) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *JourneyResponse) GetTotalDurationSeconds() int64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *JourneyResponse) GetTransitDurationSeconds() int64 {
	if x != nil {
		return x.TransitDurationSeconds
	}
	return 0
}

func (x *JourneyResponse) GetWalkingDistanceMeters() float64 {
	if x != nil {
		return x.WalkingDistanceMeters
	}
	return 0
}

func (x *JourneyResponse) GetLegs() []*JourneyLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *JourneyResponse) GetOriginStopId() string {
	if x != nil {
		return x.OriginStopId
	}
	return ""
}

func (x *JourneyResponse) GetDestinationStopId() string {
	if x != nil {
		return x.DestinationStopId
	}
	return ""
}

type JourneyLeg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Mode            string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	FromName        string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ToName          string                 `protobuf:"bytes,3,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	FromStopId      string                 `protobuf:"bytes,4,opt,name=from_stop_id,json=fromStopId,proto3" json:"from_stop_id,omitempty"`
	ToStopId        string                 `protobuf:"bytes,5,opt,name=to_stop_id,json=toStopId,proto3" json:"to_stop_id,omitempty"`
	TripId          string                 `protobuf:"bytes,6,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RouteId         string                 `protobuf:"bytes,7,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	RouteName       string                 `protobuf:"bytes,8,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	RouteLongName   string                 `protobuf:"bytes,9,opt,name=route_long_name,json=routeLongName,proto3" json:"route_long_name,omitempty"`
	DepartureTime   string                 `protobuf:"bytes,10,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime     string                 `protobuf:"bytes,11,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	DistanceMeters  float64                `protobuf:"fixed64,12,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,13,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	NodeIds         []int64                `protobuf:"varint,14,rep,packed,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	Coordinates     []*Coordinate          `protobuf:"bytes,15,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JourneyLeg) Reset() {
	*x = JourneyLeg{}
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyLeg) ProtoMessage() {}

func (x *JourneyLeg) ProtoReflect() protoreflect.Message {
	mi := &file_api_pathcraft_v1_pathcraft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyLeg.ProtoReflect.Descriptor instead.
func (*JourneyLeg) Descriptor() ([]byte, []int) {
	return file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP(), []int{5}
}

func (x *JourneyLeg) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *JourneyLeg) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *JourneyLeg) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *JourneyLeg) GetFromStopId() string {
	if x != nil {
		return x.FromStopId
	}
	return ""
}

func (x *JourneyLeg) GetToStopId() string {
	if x != nil {
		return x.ToStopId
	}
	return ""
}

func (x *JourneyLeg) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *JourneyLeg) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *JourneyLeg) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *JourneyLeg) GetRouteLongName() string {
	if x != nil {
		return x.RouteLongName
	}
	return ""
}

func (x *JourneyLeg) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *JourneyLeg) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *JourneyLeg) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *JourneyLeg) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *JourneyLeg) GetNodeIds() []int64 {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *JourneyLeg) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

var File_api_pathcraft_v1_pathcraft_proto protoreflect.FileDescriptor

const file_api_pathcraft_v1_pathcraft_proto_rawDesc = "" +
	"\n" +
	" api/pathcraft/v1/pathcraft.proto\x12\fpathcraft.v1\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\xdb\x01\n" +
	"\fRouteRequest\x120\n" +
	"\x06origin\x18\x01 \x01(\v2\x18.pathcraft.v1.CoordinateR\x06origin\x12:\n" +
	"\vdestination\x18\x02 \x01(\v2\x18.pathcraft.v1.CoordinateR\vdestination\x12,\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x18.pathcraft.v1.TravelModeR\x04mode\x12/\n" +
	"\x13include_coordinates\x18\x04 \x01(\bR\x12includeCoordinates\"\x98\x03\n" +
	"\rRouteResponse\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\x03R\anodeIds\x12:\n" +
	"\vcoordinates\x18\x02 \x03(\v2\x18.pathcraft.v1.CoordinateR\vcoordinates\x12'\n" +
	"\x0fdistance_meters\x18\x03 \x01(\x01R\x0edistanceMeters\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x03R\x0fdurationSeconds\x12$\n" +
	"\x0eorigin_node_id\x18\x05 \x01(\x03R\foriginNodeId\x12.\n" +
	"\x13destination_node_id\x18\x06 \x01(\x03R\x11destinationNodeId\x12=\n" +
	"\x1borigin_snap_distance_meters\x18\a \x01(\x01R\x18originSnapDistanceMeters\x12G\n" +
	" destination_snap_distance_meters\x18\b \x01(\x01R\x1ddestinationSnapDistanceMeters\"\xcb\x01\n" +
	"\x0eJourneyRequest\x120\n" +
	"\x06origin\x18\x01 \x01(\v2\x18.pathcraft.v1.CoordinateR\x06origin\x12:\n" +
	"\vdestination\x18\x02 \x01(\v2\x18.pathcraft.v1.CoordinateR\vdestination\x12%\n" +
	"\x0edeparture_time\x18\x03 \x01(\tR\rdepartureTime\x12$\n" +
	"\x0emax_stop_count\x18\x04 \x01(\x05R\fmaxStopCount\"\x9b\x03\n" +
	"\x0fJourneyResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12%\n" +
	"\x0edeparture_time\x18\x02 \x01(\tR\rdepartureTime\x12!\n" +
	"\farrival_time\x18\x03 \x01(\tR\varrivalTime\x124\n" +
	"\x16total_duration_seconds\x18\x04 \x01(\x03R\x14totalDurationSeconds\x128\n" +
	"\x18transit_duration_seconds\x18\x05 \x01(\x03R\x16transitDurationSeconds\x126\n" +
	"\x17walking_distance_meters\x18\x06 \x01(\x01R\x15walkingDistanceMeters\x12,\n" +
	"\x04legs\x18\a \x03(\v2\x18.pathcraft.v1.JourneyLegR\x04legs\x12$\n" +
	"\x0eorigin_stop_id\x18\b \x01(\tR\foriginStopId\x12.\n" +
	"\x13destination_stop_id\x18\t \x01(\tR\x11destinationStopId\"\x86\x04\n" +
	"\n" +
	"JourneyLeg\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\x12\x17\n" +
	"\ato_name\x18\x03 \x01(\tR\x06toName\x12 \n" +
	"\ffrom_stop_id\x18\x04 \x01(\tR\n" +
	"fromStopId\x12\x1c\n" +
	"\n" +
	"to_stop_id\x18\x05 \x01(\tR\btoStopId\x12\x17\n" +
	"\atrip_id\x18\x06 \x01(\tR\x06tripId\x12\x19\n" +
	"\broute_id\x18\a \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"route_name\x18\b \x01(\tR\trouteName\x12&\n" +
	"\x0froute_long_name\x18\t \x01(\tR\rrouteLongName\x12%\n" +
	"\x0edeparture_time\x18\n" +
	" \x01(\tR\rdepartureTime\x12!\n" +
	"\farrival_time\x18\v \x01(\tR\varrivalTime\x12'\n" +
	"\x0fdistance_meters\x18\f \x01(\x01R\x0edistanceMeters\x12)\n" +
	"\x10duration_seconds\x18\r \x01(\x03R\x0fdurationSeconds\x12\x19\n" +
	"\bnode_ids\x18\x0e \x03(\x03R\anodeIds\x12:\n" +
	"\vcoordinates\x18\x0f \x03(\v2\x18.pathcraft.v1.CoordinateR\vcoordinates*j\n" +
	"\n" +
	"TravelMode\x12\x1b\n" +
	"\x17TRAVEL_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TRAVEL_MODE_WALK\x10\x01\x12\x14\n" +
	"\x10TRAVEL_MODE_BIKE\x10\x02\x12\x13\n" +
	"\x0fTRAVEL_MODE_CAR\x10\x032\x9a\x01\n" +
	"\x0eRoutingService\x12@\n" +
	"\x05Route\x12\x1a.pathcraft.v1.RouteRequest\x1a\x1b.pathcraft.v1.RouteResponse\x12F\n" +
	"\aJourney\x12\x1c.pathcraft.v1.JourneyRequest\x1a\x1d.pathcraft.v1.JourneyResponseBAZ?github.com/danielscoffee/pathcraft/api/pathcraft/v1;pathcraftv1b\x06proto3"

var (
	file_api_pathcraft_v1_pathcraft_proto_rawDescOnce sync.Once
	file_api_pathcraft_v1_pathcraft_proto_rawDescData []byte
)

func file_api_pathcraft_v1_pathcraft_proto_rawDescGZIP() []byte {
	file_api_pathcraft_v1_pathcraft_proto_rawDescOnce.Do(func() {
		file_api_pathcraft_v1_pathcraft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pathcraft_v1_pathcraft_proto_rawDesc), len(file_api_pathcraft_v1_pathcraft_proto_rawDesc)))
	})
	return file_api_pathcraft_v1_pathcraft_proto_rawDescData
}

var file_api_pathcraft_v1_pathcraft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_pathcraft_v1_pathcraft_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_pathcraft_v1_pathcraft_proto_goTypes = []any{
	(TravelMode)(0),         // 0: pathcraft.v1.TravelMode
	(*Coordinate)(nil),      // 1: pathcraft.v1.Coordinate
	(*RouteRequest)(nil),    // 2: pathcraft.v1.RouteRequest
	(*RouteResponse)(nil),   // 3: pathcraft.v1.RouteResponse
	(*JourneyRequest)(nil),  // 4: pathcraft.v1.JourneyRequest
	(*JourneyResponse)(nil), // 5: pathcraft.v1.JourneyResponse
	(*JourneyLeg)(nil),      // 6: pathcraft.v1.JourneyLeg
}
var file_api_pathcraft_v1_pathcraft_proto_depIdxs = []int32{
	1,  // 0: pathcraft.v1.RouteRequest.origin:type_name -> pathcraft.v1.Coordinate
	1,  // 1: pathcraft.v1.RouteRequest.destination:type_name -> pathcraft.v1.Coordinate
	0,  // 2: pathcraft.v1.RouteRequest.mode:type_name -> pathcraft.v1.TravelMode
	1,  // 3: pathcraft.v1.RouteResponse.coordinates:type_name -> pathcraft.v1.Coordinate
	1,  // 4: pathcraft.v1.JourneyRequest.origin:type_name -> pathcraft.v1.Coordinate
	1,  // 5: pathcraft.v1.JourneyRequest.destination:type_name -> pathcraft.v1.Coordinate
	6,  // 6: pathcraft.v1.JourneyResponse.legs:type_name -> pathcraft.v1.JourneyLeg
	1,  // 7: pathcraft.v1.JourneyLeg.coordinates:type_name -> pathcraft.v1.Coordinate
	2,  // 8: pathcraft.v1.RoutingService.Route:input_type -> pathcraft.v1.RouteRequest
	4,  // 9: pathcraft.v1.RoutingService.Journey:input_type -> pathcraft.v1.JourneyRequest
	3,  // 10: pathcraft.v1.RoutingService.Route:output_type -> pathcraft.v1.RouteResponse
	5,  // 11: pathcraft.v1.RoutingService.Journey:output_type -> pathcraft.v1.JourneyResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_pathcraft_v1_pathcraft_proto_init() }
func file_api_pathcraft_v1_pathcraft_proto_init() {
	if File_api_pathcraft_v1_pathcraft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pathcraft_v1_pathcraft_proto_rawDesc), len(file_api_pathcraft_v1_pathcraft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pathcraft_v1_pathcraft_proto_goTypes,
		DependencyIndexes: file_api_pathcraft_v1_pathcraft_proto_depIdxs,
		EnumInfos:         file_api_pathcraft_v1_pathcraft_proto_enumTypes,
		MessageInfos:      file_api_pathcraft_v1_pathcraft_proto_msgTypes,
	}.Build()
	File_api_pathcraft_v1_pathcraft_proto = out.File
	file_api_pathcraft_v1_pathcraft_proto_goTypes = nil
	file_api_pathcraft_v1_pathcraft_proto_depIdxs = nil
}
